# Generated by Django 5.0.4 on 2024-07-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_baranggay_item_btype_item_college_item_cstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Baranggay',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Btype',
        ),
        migrations.RemoveField(
            model_name='item',
            name='College',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Cstatus',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Dbirth',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Elementary',
        ),
        migrations.RemoveField(
            model_name='item',
            name='FatherFN',
        ),
        migrations.RemoveField(
            model_name='item',
            name='FatherLN',
        ),
        migrations.RemoveField(
            model_name='item',
            name='FatherMN',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='MotherFN',
        ),
        migrations.RemoveField(
            model_name='item',
            name='MotherLN',
        ),
        migrations.RemoveField(
            model_name='item',
            name='MotherMN',
        ),
        migrations.RemoveField(
            model_name='item',
            name='MotherMaidenN',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Municipality',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Secondary',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Sex',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Vcourse',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Weight',
        ),
    ]
