# Generated by Django 5.0.4 on 2024-07-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_item_baranggay_remove_item_btype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Fname',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Lname',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Mname',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Phone',
        ),
    ]
