# Generated by Django 5.0.4 on 2024-07-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_item_address_remove_item_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Graduates',
            new_name='Graduate',
        ),
    ]
