# Generated by Django 5.0.4 on 2024-07-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_graduate_item_baranggay_item_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Graduates',
            new_name='Citizenship',
        ),
    ]
