# Generated by Django 5.0.4 on 2024-07-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_baranggay_item_barangga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Barangga',
            new_name='Baranggay',
        ),
    ]
